on: [push, workflow_dispatch]
name: Building

jobs:
  building:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Add build tools to the $PATH
        run: echo "${ANDROID_HOME}/build-tools/30.0.1" >> $GITHUB_PATH
      
      - name: Compile the mod
        run: |
          chmod +x ./gradlew
          ./gradlew release
        
      - name: Upload the client artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ github.event.repository.name }}-client-mod
          path: client/build/libs/*.jar

      - name: Upload the server artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ github.event.repository.name }}-backend-server
          path: backend/build/libs/*.jar
