on: [push, workflow_dispatch]
name: Building

jobs:
  building:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Add build tools to the $PATH
        run: echo "${ANDROID_HOME}/build-tools/33.0.2" >> $GITHUB_PATH
      
      - name: Compile the mod
        run: |
          chmod +x ./gradlew
          ./gradlew shadowJar release
        
      - name: Upload the client artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ github.event.repository.name }}-client-mod
          path: minchat-client/build/libs/*.jar

      - name: Upload the server artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ github.event.repository.name }}-backend-server
          path: minchat-backend/build/libs/*.jar

      - name: Upload the cli client artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ github.event.repository.name }}-cli-client
          path: minchat-cli/build/libs/*.jar
